import type { Metadata } from 'next';
import '../styles/global.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/sections/Footer';

import { Geist, Geist_Mono, Nanum_Pen_Script, DM_Sans } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const nanumPenScript = Nanum_Pen_Script({
  variable: '--font-display',
  subsets: ['latin'],
  weight: '400', // Nanum Pen Script only has 400 weight
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`bg-[url("/paper.png")] bg-repeat bg-left-top ${geistSans.variable} ${nanumPenScript.variable} ${geistMono.variable} ${dmSans} antialiased`}
      >
        <div className='flex min-h-screen w-full flex-col'>
          <Header />
          <main className='flex-grow'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
