import type { Metadata } from 'next';
import { Geist, Geist_Mono, Nanum_Pen_Script } from 'next/font/google';
import '../styles/global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const nanumPenScript = Nanum_Pen_Script({
  variable: '--font-display',
  subsets: ['latin'],
  weight: '400', // Nanum Pen Script only has 400 weight
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${nanumPenScript.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
